name: Crowdin Action

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches: [main]

jobs:
  synchronize-with-crowdin:
    runs-on: ubuntu-latest
    environment: crowdin

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: crowdin action
        uses: crowdin/github-action@1.4.16
        with:
          upload_translations: true
          download_translations: true
          new_branch_export_pattern: 'src/localization/locales/%two_letters_code%/**/%original_file_name%'
          source: 'src/localization/locales/en/**/*.json'
          translation: 'src/localization/locales/%locale%/**/%original_file_name%'
          base_url: 'https://ava-labs.crowdin.com'
          project_id: ${{ secrets.CROWDIN_PROJECT_ID }}
          token: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
