name: PR checks (Next Gen)
on:
  push:
    paths:
      - apps/next/**
jobs:
  lint:
    name: Lint and build (Next Gen)
    runs-on: ubuntu-latest
    environment: alpha
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: enable corepack
        run: |
          corepack enable
      - name: Create env file
        run: |
          touch .env.production
          echo 'POSTHOG_KEY="${{ secrets.POSTHOG_KEY }}"' >> .env.production
          echo 'GLACIER_URL="${{ secrets.GLACIER_URL }}"' >> .env.production
          echo 'PROXY_URL="${{ secrets.PROXY_URL }}"' >> .env.production
          echo 'CORE_EXTENSION_LANDING_URL="${{ secrets.CORE_EXTENSION_LANDING_URL }}"' >> .env.production
      - name: Install dependencies
        run: |
          yarn install
          yarn allow-scripts
      - name: Lint
        run: yarn lint:next
      - name: Typecheck
        run: yarn typecheck:next
      - name: Check if localization was updated
        run: |
          yarn scanner:next
          git --no-pager diff
          if [[ $(git status --short) == '' ]]; then exit 0; else exit 1; fi
      - name: Test
        run: yarn test:next
      - name: Build extension
        run: yarn build:next
